# -*- coding: utf-8 -*-
"""LogisticRegression/Social_Network_Ads.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyujzhRgfeB-yS_OV21M4DoKaBhU61V_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Social_Network_Ads.csv')

df.head()

X=df[['Age','EstimatedSalary']]
y=df['Purchased']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

standard=StandardScaler()
X_train=standard.fit_transform(X_train)
X_test=standard.transform(X_test)

lg=LogisticRegression()
lg.fit(X_train,y_train)

y_pred=lg.predict(X_test)

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

from sklearn.model_selection import GridSearchCV

# 1. Define the base model
base_model = LogisticRegression(max_iter=1000, random_state=42)

# 2. Define the hyperparameter grid
param_grid = [
    {
        'solver': ['liblinear', 'saga'],
        'penalty': ['l1', 'l2'],
        'C': [0.001, 0.01, 0.1, 1, 10, 100],
    },
    {
        'solver': ['lbfgs'],
        'penalty': ['l2', None],
        'C': [0.001, 0.01, 0.1, 1, 10, 100],
    }
]

# 3. Instantiate GridSearchCV (5-fold cross-validation)
grid_search = GridSearchCV(
    estimator=base_model,
    param_grid=param_grid,
    cv=5,                  # 5-fold cross validation
    scoring='accuracy',    # Metric to optimize
    n_jobs=-1,             # Use all CPU cores
    verbose=1
)

# 4. Fit Grid Search on training data ONLY
grid_search.fit(X_train, y_train)

# 5. Output the best hyperparameters and cross-validation score
print("Best Hyperparameters:", grid_search.best_params_)
print(f"Best Cross-Validation Accuracy: {grid_search.best_score_:.4f}")

# 6. Evaluate the best model on the unseen Test Set
best_model = grid_search.best_estimator_
y_pred_tuned = best_model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print(f"\nTuned Test Set Accuracy: {accuracy_score(y_test, y_pred_tuned):.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_tuned))

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# 1. Linear SVM (Draws a straight line, similar to Logistic Regression)
svm_linear = SVC(kernel='linear', C=1.0, random_state=42)
svm_linear.fit(X_train, y_train)
y_pred_linear = svm_linear.predict(X_test)

print(f"Linear SVM Test Accuracy: {accuracy_score(y_test, y_pred_linear):.4f}")

# 2. Non-Linear Kernel SVM (RBF Kernel - Curves around data points)
svm_rbf = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
svm_rbf.fit(X_train, y_train)
y_pred_rbf = svm_rbf.predict(X_test)

print(f"RBF Kernel SVM Test Accuracy: {accuracy_score(y_test, y_pred_rbf):.4f}")

# Create a mesh grid of points
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(
    np.arange(start=X_set[:, 0].min() - 1, stop=X_set[:, 0].max() + 1, step=0.01),
    np.arange(start=X_set[:, 1].min() - 1, stop=X_set[:, 1].max() + 1, step=0.01)
)

# Plot decision boundary
plt.figure(figsize=(8, 6))
plt.contourf(
    X1, X2,
    svm_rbf.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
    alpha=0.25, cmap=plt.cm.coolwarm
)

# Scatter plot test points
sns.scatterplot(x=X_set[:, 0], y=X_set[:, 1], hue=y_set, palette=['red', 'green'])
plt.title('RBF Kernel SVM Decision Boundary (Test Set)')
plt.xlabel('Age (Scaled)')
plt.ylabel('Estimated Salary (Scaled)')
plt.show()