# -*- coding: utf-8 -*-
"""MultipleLinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohwQ_xLejfPpT43WMpe7A4CyrtM9m5ew
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df=pd.read_csv('/content/insurance.csv')

X=df[['age']]
y=df['charges']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

df.isnull().sum()

df.info()

df.head()

df[['age','charges']].corr()

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.scatter(X_train_scaled, y_train)
plt.title('Scaled Age vs Charges (Training Set)')
plt.xlabel('Scaled Age')
plt.ylabel('Charges')

plt.subplot(1, 2, 2)
plt.scatter(X_test_scaled, y_test)
plt.title('Scaled Age vs Charges (Test Set)')
plt.xlabel('Scaled Age')
plt.ylabel('Charges')

plt.tight_layout()
plt.show()

df.shape

df.describe()

# Check target distribution (e.g., SalePrice)
plt.figure(figsize=(8, 4))
sns.histplot(df['charges'], kde=True, color='blue')
plt.title('Charges varition')
plt.xlabel('Charges')
plt.ylabel('Frequency')
plt.show()

# Check skewness number (> 0.75 or < -0.75 indicates skewness)
print("Target Skewness:", df['charges'].skew())

"""### Outlier Removal using IQR for `y_train`

Since the `charges` distribution is skewed and contains high values that might be considered outliers, we'll use the Interquartile Range (IQR) method to identify and remove them from the training set. This helps the model focus on the more typical range of charges. We'll then re-scale the `X_train` data.
"""

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for y_train
Q1 = y_train.quantile(0.25)
Q3 = y_train.quantile(0.75)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1: {Q1:.2f}")
print(f"Q3: {Q3:.2f}")
print(f"IQR: {IQR:.2f}")
print(f"Lower Bound for Outliers: {lower_bound:.2f}")
print(f"Upper Bound for Outliers: {upper_bound:.2f}")

# Identify non-outlier indices in y_train
non_outlier_indices = y_train[(y_train >= lower_bound) & (y_train <= upper_bound)].index

# Filter X_train and y_train based on these indices
X_train_cleaned = X_train.loc[non_outlier_indices]
y_train_cleaned = y_train.loc[non_outlier_indices]

print(f"\nOriginal training samples: {len(y_train)}")
print(f"Training samples after outlier removal: {len(y_train_cleaned)}")

# Re-scale X_train_cleaned using the *already fitted* scaler
X_train_scaled_cleaned = scaler.transform(X_train_cleaned)

print("\nX_train_cleaned and y_train_cleaned created and X_train_scaled_cleaned re-scaled.")

"""We can visualize the cleaned training data to see the effect of outlier removal:"""

plt.figure(figsize=(8, 6))
plt.scatter(X_train_scaled_cleaned, y_train_cleaned)
plt.title('Scaled Age vs Charges (Cleaned Training Set - Outliers Removed)')
plt.xlabel('Scaled Age')
plt.ylabel('Charges')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""### Train and Evaluate Linear Regression Model"""

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train_scaled_cleaned, y_train_cleaned)

# Make predictions on the cleaned training set
y_train_pred = model.predict(X_train_scaled_cleaned)

# Make predictions on the scaled test set
y_test_pred = model.predict(X_test_scaled)

# Evaluate the model on the training set
mse_train = mean_squared_error(y_train_cleaned, y_train_pred)
r2_train = r2_score(y_train_cleaned, y_train_pred)

# Evaluate the model on the test set
mse_test = mean_squared_error(y_test, y_test_pred)
r2_test = r2_score(y_test, y_test_pred)

print("\n--- Model Performance ---")
print(f"Training MSE: {mse_train:.2f}")
print(f"Training R^2: {r2_train:.2f}")
print(f"Test MSE: {mse_test:.2f}")
print(f"Test R^2: {r2_test:.2f}")

print(f"\nModel Coefficients: {model.coef_[0]:.2f}")
print(f"Model Intercept: {model.intercept_:.2f}")

"""### Multiple Linear Regression with 'age', 'bmi', and 'children'"""

# 1. Define X and y for multiple regression
X_multi = df[['age', 'bmi', 'children']]
y_multi = df['charges']

print("Features (X_multi) and Target (y_multi) defined.")

# 2. Split data into training and testing sets
X_train_multi, X_test_multi, y_train_multi, y_test_multi = train_test_split(X_multi, y_multi, test_size=0.2, random_state=42)

print(f"X_train_multi shape: {X_train_multi.shape}")
print(f"X_test_multi shape: {X_test_multi.shape}")
print(f"y_train_multi shape: {y_train_multi.shape}")
print(f"y_test_multi shape: {y_test_multi.shape}")

# 3. Scale the features using StandardScaler
# Initialize a NEW scaler for these new features
scaler_multi = StandardScaler()

X_train_scaled_multi = scaler_multi.fit_transform(X_train_multi)
X_test_scaled_multi = scaler_multi.transform(X_test_multi)

print("Features scaled using StandardScaler.")

"""### Outlier Removal for `y_train_multi`

Similar to the previous step, we'll remove outliers from the target variable (`y_train_multi`) in the training set using the IQR method. The corresponding rows will also be removed from `X_train_scaled_multi`.
"""

# Calculate Q1 and Q3 for y_train_multi
Q1_multi = y_train_multi.quantile(0.25)
Q3_multi = y_train_multi.quantile(0.75)
IQR_multi = Q3_multi - Q1_multi

# Define outlier bounds
lower_bound_multi = Q1_multi - 1.5 * IQR_multi
upper_bound_multi = Q3_multi + 1.5 * IQR_multi

print(f"Q1_multi: {Q1_multi:.2f}")
print(f"Q3_multi: {Q3_multi:.2f}")
print(f"IQR_multi: {IQR_multi:.2f}")
print(f"Lower Bound for Outliers (multi): {lower_bound_multi:.2f}")
print(f"Upper Bound for Outliers (multi): {upper_bound_multi:.2f}")

# Identify non-outlier indices in y_train_multi
non_outlier_indices_multi = y_train_multi[(y_train_multi >= lower_bound_multi) & (y_train_multi <= upper_bound_multi)].index

# Filter X_train_scaled_multi and y_train_multi
X_train_scaled_cleaned_multi = X_train_scaled_multi[X_train_multi.index.isin(non_outlier_indices_multi)]
y_train_cleaned_multi = y_train_multi.loc[non_outlier_indices_multi]

print(f"\nOriginal training samples (multi): {len(y_train_multi)}")
print(f"Training samples after outlier removal (multi): {len(y_train_cleaned_multi)}")

"""### Train and Evaluate Multiple Linear Regression Model"""

# 5. Train the Linear Regression model
model_multi = LinearRegression()
model_multi.fit(X_train_scaled_cleaned_multi, y_train_cleaned_multi)

# 6. Make predictions
y_train_pred_multi = model_multi.predict(X_train_scaled_cleaned_multi)
y_test_pred_multi = model_multi.predict(X_test_scaled_multi)

# Evaluate the model on training set
mse_train_multi = mean_squared_error(y_train_cleaned_multi, y_train_pred_multi)
r2_train_multi = r2_score(y_train_cleaned_multi, y_train_pred_multi)

# Evaluate the model on test set
mse_test_multi = mean_squared_error(y_test_multi, y_test_pred_multi)
r2_test_multi = r2_score(y_test_multi, y_test_pred_multi)

print("\n--- Multiple Linear Regression Model Performance ---")
print(f"Training MSE: {mse_train_multi:.2f}")
print(f"Training R^2: {r2_train_multi:.2f}")
print(f"Test MSE: {mse_test_multi:.2f}")
print(f"Test R^2: {r2_test_multi:.2f}")

print("\nModel Coefficients:")
for feature, coef in zip(X_multi.columns, model_multi.coef_):
    print(f"  {feature}: {coef:.2f}")
print(f"Model Intercept: {model_multi.intercept_:.2f}")

"""### Multiple Linear Regression with Numerical and Categorical Features"""

# 1. One-Hot Encode Categorical Features
df_encoded = pd.get_dummies(df, columns=['sex', 'smoker', 'region'], drop_first=True)

# 2. Define X and y with all relevant features
X_full = df_encoded[['age', 'bmi', 'children', 'sex_male', 'smoker_yes', 'region_northwest', 'region_southeast', 'region_southwest']]
y_full = df_encoded['charges']

print("Features (X_full) and Target (y_full) defined with encoded categorical variables.")
print("Shape of X_full:", X_full.shape)

# 3. Split data into training and testing sets
X_train_full, X_test_full, y_train_full, y_test_full = train_test_split(X_full, y_full, test_size=0.2, random_state=42)

print(f"X_train_full shape: {X_train_full.shape}")
print(f"X_test_full shape: {X_test_full.shape}")

# 4. Scale only the numerical features
# Identify numerical columns for scaling
numerical_cols = ['age', 'bmi', 'children']

# Initialize a new scaler for the full model
scaler_full = StandardScaler()

# Fit and transform on X_train_full numerical columns
X_train_full_scaled_numerical = scaler_full.fit_transform(X_train_full[numerical_cols])
X_test_full_scaled_numerical = scaler_full.transform(X_test_full[numerical_cols])

# Create DataFrames for scaled numerical features
X_train_full_scaled_numerical_df = pd.DataFrame(X_train_full_scaled_numerical, columns=numerical_cols, index=X_train_full.index)
X_test_full_scaled_numerical_df = pd.DataFrame(X_test_full_scaled_numerical, columns=numerical_cols, index=X_test_full.index)

# Combine scaled numerical features with original (unscaled) categorical features
X_train_scaled_full = pd.concat([X_train_full_scaled_numerical_df, X_train_full.drop(columns=numerical_cols)], axis=1)
X_test_scaled_full = pd.concat([X_test_full_scaled_numerical_df, X_test_full.drop(columns=numerical_cols)], axis=1)

print("Numerical features scaled and combined with categorical features.")
print("Shape of X_train_scaled_full:", X_train_scaled_full.shape)
print("Shape of X_test_scaled_full:", X_test_scaled_full.shape)

"""### Outlier Removal for `y_train_full`

We'll re-apply the outlier removal process to the target variable (`y_train_full`) of this new, larger training set, ensuring consistency in our data cleaning.
"""

# Calculate Q1 and Q3 for y_train_full
Q1_full = y_train_full.quantile(0.25)
Q3_full = y_train_full.quantile(0.75)
IQR_full = Q3_full - Q1_full

# Define outlier bounds
lower_bound_full = Q1_full - 1.5 * IQR_full
upper_bound_full = Q3_full + 1.5 * IQR_full

print(f"Q1_full: {Q1_full:.2f}")
print(f"Q3_full: {Q3_full:.2f}")
print(f"IQR_full: {IQR_full:.2f}")
print(f"Lower Bound for Outliers (full): {lower_bound_full:.2f}")
print(f"Upper Bound for Outliers (full): {upper_bound_full:.2f}")

# Identify non-outlier indices in y_train_full
non_outlier_indices_full = y_train_full[(y_train_full >= lower_bound_full) & (y_train_full <= upper_bound_full)].index

# Filter X_train_scaled_full and y_train_full
X_train_scaled_cleaned_full = X_train_scaled_full.loc[non_outlier_indices_full]
y_train_cleaned_full = y_train_full.loc[non_outlier_indices_full]

print(f"\nOriginal training samples (full): {len(y_train_full)}")
print(f"Training samples after outlier removal (full): {len(y_train_cleaned_full)}")

"""### Train and Evaluate Full Multiple Linear Regression Model"""

# 6. Train the Linear Regression model
model_full = LinearRegression()
model_full.fit(X_train_scaled_cleaned_full, y_train_cleaned_full)

# 7. Make predictions
y_train_pred_full = model_full.predict(X_train_scaled_cleaned_full)
y_test_pred_full = model_full.predict(X_test_scaled_full)

# Evaluate the model on training set
mse_train_full = mean_squared_error(y_train_cleaned_full, y_train_pred_full)
r2_train_full = r2_score(y_train_cleaned_full, y_train_pred_full)

# Evaluate the model on test set
mse_test_full = mean_squared_error(y_test_full, y_test_pred_full)
r2_test_full = r2_score(y_test_full, y_test_pred_full)

print("\n--- Full Multiple Linear Regression Model Performance ---")
print(f"Training MSE: {mse_train_full:.2f}")
print(f"Training R^2: {r2_train_full:.2f}")
print(f"Test MSE: {mse_test_full:.2f}")
print(f"Test R^2: {r2_test_full:.2f}")

print("\nModel Coefficients:")
for feature, coef in zip(X_full.columns, model_full.coef_):
    print(f"  {feature}: {coef:.2f}")
print(f"Model Intercept: {model_full.intercept_:.2f}")

"""### Simple Linear Regression with 'smoker' (Encoded) as the Sole Predictor"""

# 1. One-Hot Encode 'smoker' feature
df_smoker_encoded = pd.get_dummies(df, columns=['smoker'], drop_first=True)

# 2. Define X (smoker_yes) and y (charges)
X_smoker = df_smoker_encoded[['smoker_yes']]
y_smoker = df_smoker_encoded['charges']

print("Features (X_smoker) and Target (y_smoker) defined with encoded 'smoker' variable.")
print("Shape of X_smoker:", X_smoker.shape)

# 3. Split data into training and testing sets
X_train_smoker, X_test_smoker, y_train_smoker, y_test_smoker = train_test_split(X_smoker, y_smoker, test_size=0.2, random_state=42)

print(f"X_train_smoker shape: {X_train_smoker.shape}")
print(f"X_test_smoker shape: {X_test_smoker.shape}")

"""#### Outlier Removal for `y_train_smoker`

We'll re-apply the outlier removal process to the target variable (`y_train_smoker`) to maintain consistency in our data cleaning.
"""

# Calculate Q1 and Q3 for y_train_smoker
Q1_smoker = y_train_smoker.quantile(0.25)
Q3_smoker = y_train_smoker.quantile(0.75)
IQR_smoker = Q3_smoker - Q1_smoker

# Define outlier bounds
lower_bound_smoker = Q1_smoker - 1.5 * IQR_smoker
upper_bound_smoker = Q3_smoker + 1.5 * IQR_smoker

print(f"Q1_smoker: {Q1_smoker:.2f}")
print(f"Q3_smoker: {Q3_smoker:.2f}")
print(f"IQR_smoker: {IQR_smoker:.2f}")
print(f"Lower Bound for Outliers (smoker): {lower_bound_smoker:.2f}")
print(f"Upper Bound for Outliers (smoker): {upper_bound_smoker:.2f}")

# Identify non-outlier indices in y_train_smoker
non_outlier_indices_smoker = y_train_smoker[(y_train_smoker >= lower_bound_smoker) & (y_train_smoker <= upper_bound_smoker)].index

# Filter X_train_smoker and y_train_smoker
X_train_cleaned_smoker = X_train_smoker.loc[non_outlier_indices_smoker]
y_train_cleaned_smoker = y_train_smoker.loc[non_outlier_indices_smoker]

print(f"\nOriginal training samples (smoker): {len(y_train_smoker)}")
print(f"Training samples after outlier removal (smoker): {len(y_train_cleaned_smoker)}")

# 5. Train the Linear Regression model
model_smoker = LinearRegression()
model_smoker.fit(X_train_cleaned_smoker, y_train_cleaned_smoker)

# 6. Make predictions
y_train_pred_smoker = model_smoker.predict(X_train_cleaned_smoker)
y_test_pred_smoker = model_smoker.predict(X_test_smoker)

# Evaluate the model on training set
mse_train_smoker = mean_squared_error(y_train_cleaned_smoker, y_train_pred_smoker)
r2_train_smoker = r2_score(y_train_cleaned_smoker, y_train_pred_smoker)

# Evaluate the model on test set
mse_test_smoker = mean_squared_error(y_test_smoker, y_test_pred_smoker)
r2_test_smoker = r2_score(y_test_smoker, y_test_pred_smoker)

print("\n--- Simple Linear Regression Model (Smoker) Performance ---")
print(f"Training MSE: {mse_train_smoker:.2f}")
print(f"Training R^2: {r2_train_smoker:.2f}")
print(f"Test MSE: {mse_test_smoker:.2f}")
print(f"Test R^2: {r2_test_smoker:.2f}")

print("\nModel Coefficients:")
for feature, coef in zip(X_smoker.columns, model_smoker.coef_):
    print(f"  {feature}: {coef:.2f}")
print(f"Model Intercept: {model_smoker.intercept_:.2f}")